### ISSUE TITLE
./gradlew installAppProcess  error

### ISSUE THREAD

**Issue by liberatorqjw** [dessertlab/fantastic_beasts#1]
when i run "./gradlew installAppProcess"
i get the error
```
FAILURE: Build failed with an exception.

* What went wrong:
Task 'installAppProcess' not found in root project 'fantastic_beasts'
```

**Comment by akiannillo** [comment]
It should work now with commit 187cd21991d9e30d736f9be7f6f56d9bce13f015.
We moved from our internal repository to GitHub, and these files were left behind.

**Comment by liberatorqjw** [comment]
Thanks for your help, I install the app. but it occurred another error as follow:
when I test the service in the device of Nexus 6p (7.1.2)
```
./chizpurfle -service media.player
```
it is the error, it may be the stalker_server.so does not inject in the target process(media_server).
```
Welcome, I am a Chizpurfle!
8388608, 201326592, 7943488
Chizpurfle evolutionary fuzzer started
injecting server in process /system/bin/mediaserver with pid 5611
Not ready to connect the local socket (trial 1)
Not ready to connect the local socket (trial 2)
Not ready to connect the local socket (trial 3)
Not ready to connect the local socket (trial 4)
Not ready to connect the local socket (trial 5)
Not ready to connect the local socket (trial 6)
Not ready to connect the local socket (trial 7)
Not ready to connect the local socket (trial 8)
Not ready to connect the local socket (trial 9)

```

**Comment by akiannillo** [comment]
This is another issue. I mark this as closed and you can open a new one. By the way, be sure you started the frida-server.
